name: LifeStealX
version: '${project.version}'
main: org.strassburger.lifestealz.LifeStealZ
api-version: '1.19'
authors: [Kartoffelchips, ItsArio]
description: LifeStealX - The Ultimate LifeSteal SMP Plugin!

softdepend:
    - PlaceholderAPI
    - WorldGuard
    - Geyser-Spigot

commands:
    lifesteal:
        aliases:
            - ls
        description: lifestealx admin commands
        permission-message: §cYou don't have permission to use this command!
    eliminate:
        permission: lifestealx.admin.eliminate
        description: eliminate a player
        permission-message: §cYou don't have permission to use this command!
    revive:
        permission: lifestealx.admin.revive
        description: revive a player
        permission-message: §cYou don't have permission to use this command!
    withdrawheart:
        permission: lifestealx.withdraw
        description: withdraw a heart
        permission-message: §cYou don't have permission to use this command!
    hearts:
        permission: lifesteax.viewhearts
        description: view other players max hearts
        permission-message: §cYou don't have permission to use this command!

permissions:
    lifestealz.managedata:
        description: permission to manage data
        default: op
    lifestealz.admin.reload:
        description: permission to reload plugin
        default: op
    lifestealz.admin.setlife:
        description: set a players hearts
        default: op
    lifestealz.admin.giveitem:
        description: give custom items to player
        default: op
    lifestealz.admin.eliminate:
        description: eliminate a player
        default: op
    lifestealz.admin.revive:
        description: revive a player
        default: op
    lifestealz.bypassrevivelimit:
        description: bypass the player revive limit
        default: op
    lifestealz.withdraw:
        description: withdraw a heart
        default: true
    lifestealz.revive:
        description: allow to revive player
        default: true
    lifestealz.viewrecipes:
        description: allows to view recipes
        default: true
    lifestealz.help:
        description: allows to see help page
        default: true
    lifestealz.viewhearts:
        description: allows to view other players max hearts
        default: true